// AutoDQA static console — Cognito login (USER_PASSWORD_AUTH) + direct streaming
// invoke of the AgentCore Runtime with the bearer token. No framework, no SDK.
// Config (region, clientId, runtimeArn) comes from config.js (generated by
// make_config.py).
"use strict";

const CFG = window.AUTODQA_CONFIG;
let accessToken = null;

const $ = (id) => document.getElementById(id);

// ---- Cognito USER_PASSWORD_AUTH (unauthenticated Cognito API, browser-callable) ----
async function login(email, password) {
  const res = await fetch(`https://cognito-idp.${CFG.region}.amazonaws.com/`, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-amz-json-1.1",
      "X-Amz-Target": "AWSCognitoIdentityProviderService.InitiateAuth",
    },
    body: JSON.stringify({
      AuthFlow: "USER_PASSWORD_AUTH",
      ClientId: CFG.clientId,
      AuthParameters: { USERNAME: email, PASSWORD: password },
    }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.message || JSON.stringify(data));
  return data.AuthenticationResult.AccessToken;
}

// ---- Direct streaming invoke of the runtime (SSE over fetch) ----
async function invoke(task, onEvent) {
  const escaped = encodeURIComponent(CFG.runtimeArn);
  const url = `https://bedrock-agentcore.${CFG.region}.amazonaws.com/runtimes/${escaped}/invocations?qualifier=DEFAULT`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      "X-Amzn-Bedrock-AgentCore-Runtime-Session-Id": "web-" + crypto.randomUUID(),
    },
    body: JSON.stringify({ task }),
  });
  if (!res.ok) { onEvent({ type: "error", content: `HTTP ${res.status}: ${await res.text()}` }); return; }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    let nl;
    while ((nl = buf.indexOf("\n")) >= 0) {
      const line = buf.slice(0, nl).trim();
      buf = buf.slice(nl + 1);
      if (!line.startsWith("data:")) continue;
      const payload = line.slice(5).trim();
      try { onEvent(JSON.parse(payload)); }
      catch { onEvent({ type: "raw", content: payload }); }
    }
  }
}

// ---- Rendering ----
function addLine(cls, text) {
  const div = document.createElement("div");
  div.className = "msg " + cls;
  div.textContent = text;
  $("stream").appendChild(div);
  $("stream").scrollTop = $("stream").scrollHeight;
}

function renderEvent(ev) {
  const c = ev.content;
  if (ev.type === "error") return addLine("error", typeof c === "string" ? c : JSON.stringify(c));
  if (ev.type === "ToolMessage") {
    const txt = Array.isArray(c) ? c.map((b) => b.text || "").join("") : c;
    return addLine("result", "→ " + txt);
  }
  if (ev.type === "AIMessage") {
    if (typeof c === "string") { if (c.trim()) addLine("assistant", c); return; }
    for (const b of c || []) {
      if (b.type === "text" && b.text) addLine("assistant", b.text);
      else if (b.type === "tool_use") addLine("tool", `🔧 ${b.name} ${JSON.stringify(b.input)}`);
    }
  }
  // HumanMessage echoes the task we already showed — skip.
}

// ---- Wiring ----
$("loginBtn").addEventListener("click", async () => {
  $("loginErr").textContent = "";
  $("loginBtn").disabled = true;
  try {
    accessToken = await login($("email").value.trim(), $("password").value);
    $("loginPanel").hidden = true;
    $("appPanel").hidden = false;
    $("who").textContent = $("email").value.trim();
    $("task").focus();
  } catch (e) {
    $("loginErr").textContent = e.message;
  } finally {
    $("loginBtn").disabled = false;
  }
});

$("taskForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const task = $("task").value.trim();
  if (!task) return;
  addLine("user", task);
  $("task").value = "";
  $("send").disabled = true;
  try {
    await invoke(task, renderEvent);
  } catch (e) {
    addLine("error", String(e));
  } finally {
    $("send").disabled = false;
    $("task").focus();
  }
});
