CREATE PROCEDURE etl.load_DEMOGRAPHIC
AS
BEGIN
    SET NOCOUNT ON;
    TRUNCATE TABLE cdm.DEMOGRAPHIC;
    INSERT INTO cdm.DEMOGRAPHIC (PATID, BIRTH_DATE, SEX, RACE, HISPANIC, RAW_SEX, SOURCE)
    SELECT PATID, BIRTH_DATE, SEX, RACE, HISPANIC, RAW_SEX, SOURCE
    FROM etl.DEMOGRAPHIC;
    -- Post-load row count audit
    INSERT INTO etl.load_audit (table_name, row_count, load_dt)
    SELECT 'DEMOGRAPHIC', COUNT(*), GETDATE() FROM cdm.DEMOGRAPHIC;
END
