CREATE PROCEDURE etl.load_ENCOUNTER
AS
BEGIN
    SET NOCOUNT ON;
    TRUNCATE TABLE cdm.ENCOUNTER;
    INSERT INTO cdm.ENCOUNTER (ENCOUNTERID, PATID, ADMIT_DATE, DISCHARGE_DATE, ENC_TYPE, FACILITY_LOCATION, SOURCE)
    SELECT ENCOUNTERID, PATID, ADMIT_DATE, DISCHARGE_DATE, ENC_TYPE, FACILITY_LOCATION, SOURCE
    FROM etl.ENCOUNTER_EPIC
    UNION ALL
    SELECT ENCOUNTERID, PATID, ADMIT_DATE, DISCHARGE_DATE, ENC_TYPE, FACILITY_LOCATION, SOURCE
    FROM etl.ENCOUNTER_ALLSCRIPTS
    UNION ALL
    SELECT ENCOUNTERID, PATID, ADMIT_DATE, DISCHARGE_DATE, ENC_TYPE, FACILITY_LOCATION, SOURCE
    FROM etl.ENCOUNTER_GECBI;
END
